# Generated by Django 5.2.14 on 2026-05-07 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lesson',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], max_length=30),
        ),
        migrations.AddField(
            model_name='lesson',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['subject', 'date'], name='academy_les_subject_7ff664_idx'),
        ),
    ]
