# Generated by Django 5.2.14 on 2026-05-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_lesson_lesson_data_lesson_progress_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Qaida Nooraniyya', 'Qaida Nooraniyya'), ('Nazira Quran', 'Nazira Quran'), ('Quran Memorization', 'Quran Memorization'), ('Tajweed', 'Tajweed'), ('Duas & Sunnah', 'Duas & Sunnah'), ('Arabic Basics', 'Arabic Basics'), ('Other', 'Other')], max_length=120)),
                ('custom_subject_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='academy.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='academy_stu_student_45c897_idx'), models.Index(fields=['subject', 'is_active'], name='academy_stu_subject_b07194_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'custom_subject_name'), name='unique_subject_per_student')],
            },
        ),
    ]
