# Generated by Django 5.2.14 on 2026-05-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_studentsubject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=120)),
                ('week_1_plan', models.TextField(blank=True)),
                ('week_2_plan', models.TextField(blank=True)),
                ('week_3_plan', models.TextField(blank=True)),
                ('week_4_plan', models.TextField(blank=True)),
                ('week_5_plan', models.TextField(blank=True)),
                ('target_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_monthly_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_lesson_plans', to='academy.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_lesson_plans', to='academy.teacherprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'year', 'month'], name='academy_mon_student_18b743_idx'), models.Index(fields=['teacher', 'year', 'month'], name='academy_mon_teacher_bd775f_idx'), models.Index(fields=['subject', 'year', 'month'], name='academy_mon_subject_48ff8b_idx'), models.Index(fields=['status'], name='academy_mon_status_e6ec79_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'teacher', 'month', 'year', 'subject'), name='unique_monthly_plan_per_student_subject')],
            },
        ),
    ]
