# Generated by Django 5.2.14 on 2026-05-09 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_monthlylessonplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlylessonplan',
            name='week_1_plan',
        ),
        migrations.RemoveField(
            model_name='monthlylessonplan',
            name='week_2_plan',
        ),
        migrations.RemoveField(
            model_name='monthlylessonplan',
            name='week_3_plan',
        ),
        migrations.RemoveField(
            model_name='monthlylessonplan',
            name='week_4_plan',
        ),
        migrations.RemoveField(
            model_name='monthlylessonplan',
            name='week_5_plan',
        ),
        migrations.AddField(
            model_name='monthlylessonplan',
            name='plan_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MonthlyLessonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('summary_text', models.TextField()),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('teacher', 'Teacher'), ('ai', 'AI'), ('system', 'System')], default='teacher', max_length=20)),
                ('generated_from_lessons_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_monthly_lesson_summaries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_lesson_summaries', to='academy.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_lesson_summaries', to='academy.teacherprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'year', 'month'], name='academy_mon_student_77d7f3_idx'), models.Index(fields=['teacher', 'year', 'month'], name='academy_mon_teacher_018125_idx'), models.Index(fields=['subject', 'year', 'month'], name='academy_mon_subject_8cf41f_idx'), models.Index(fields=['source'], name='academy_mon_source_c45c2f_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'teacher', 'month', 'year', 'subject'), name='unique_monthly_summary_per_student_subject')],
            },
        ),
    ]
