# Generated by Django 5.2.14 on 2026-05-18 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_remove_monthlylessonplan_week_1_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('edit_permission_until', models.DateTimeField(blank=True, null=True)),
                ('edit_permission_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_lesson_reports', to=settings.AUTH_USER_MODEL)),
                ('edit_permission_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_daily_lesson_edit_permissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_lesson_reports', to='academy.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_lesson_reports', to='academy.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLessonSubjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('topic_summary', models.CharField(max_length=500)),
                ('progress_status', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('lesson_data', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_entries', to='academy.dailylessonreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dailylessonreport',
            index=models.Index(fields=['student', 'date'], name='academy_dai_student_086e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylessonreport',
            index=models.Index(fields=['teacher', 'date'], name='academy_dai_teacher_bcc6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylessonreport',
            index=models.Index(fields=['date'], name='academy_dai_date_913df2_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailylessonreport',
            constraint=models.UniqueConstraint(fields=('student', 'teacher', 'date'), name='unique_daily_lesson_report_per_student_teacher_date'),
        ),
        migrations.AddIndex(
            model_name='dailylessonsubjectentry',
            index=models.Index(fields=['subject'], name='academy_dai_subject_8b902c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylessonsubjectentry',
            index=models.Index(fields=['progress_status'], name='academy_dai_progres_b8ec22_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylessonsubjectentry',
            index=models.Index(fields=['sort_order'], name='academy_dai_sort_or_0a7b35_idx'),
        ),
    ]
