# Generated by Django 5.2.14 on 2026-05-18 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_dailylessonreport_dailylessonsubjectentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('can_write', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_lesson_access_permissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_access_permissions', to='academy.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_access_permissions', to='academy.teacherprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'teacher', 'lesson_date', 'is_active'], name='academy_les_student_ed9e7b_idx'), models.Index(fields=['teacher', 'lesson_date'], name='academy_les_teacher_800fe8_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'teacher', 'lesson_date'), name='unique_lesson_access_permission_per_student_teacher_date')],
            },
        ),
        migrations.CreateModel(
            name='LessonWritePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('write', 'Write Lesson'), ('edit', 'Edit Lesson')], default='write', max_length=20)),
                ('lesson_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_lesson_permissions', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='write_permissions', to='academy.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_write_permissions', to='academy.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_write_permissions', to='academy.teacherprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'teacher', 'lesson_date'], name='academy_les_student_032461_idx'), models.Index(fields=['teacher', 'is_active'], name='academy_les_teacher_6d234d_idx'), models.Index(fields=['permission_type', 'is_active'], name='academy_les_permiss_95813a_idx'), models.Index(fields=['expires_at'], name='academy_les_expires_f008ab_idx')],
            },
        ),
    ]
