# Generated by Django 5.2.14 on 2026-05-18 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_lessonaccesspermission_lessonwritepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonaccesspermission',
            options={'ordering': ['-lesson_date', '-updated_at']},
        ),
        migrations.RemoveConstraint(
            model_name='lessonaccesspermission',
            name='unique_lesson_access_permission_per_student_teacher_date',
        ),
        migrations.RemoveIndex(
            model_name='lessonaccesspermission',
            name='academy_les_student_ed9e7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonaccesspermission',
            name='academy_les_teacher_800fe8_idx',
        ),
        migrations.RemoveField(
            model_name='lessonaccesspermission',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='lessonaccesspermission',
            name='can_write',
        ),
        migrations.AddField(
            model_name='lessonaccesspermission',
            name='access_type',
            field=models.CharField(choices=[('add', 'Allow Add'), ('edit', 'Allow Edit')], default='write', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonaccesspermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_lesson_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonaccesspermission',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lessonwritepermission',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_lesson_access_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lessonaccesspermission',
            index=models.Index(fields=['teacher', 'student', 'lesson_date', 'access_type'], name='academy_les_teacher_163bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonaccesspermission',
            index=models.Index(fields=['lesson_date', 'is_active'], name='academy_les_lesson__508b24_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonaccesspermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('teacher', 'student', 'lesson_date', 'access_type'), name='unique_active_lesson_access_permission'),
        ),
    ]
