# Generated by Django 5.2.14 on 2026-05-19 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_lessonaccesspermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('subject', models.CharField(blank=True, default='', max_length=120)),
                ('request_type', models.CharField(choices=[('add', 'Add Lesson'), ('edit', 'Edit Lesson')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('coordinator_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='lessonwritepermission',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='lessonwritepermission',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonwritepermission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lessonwritepermission',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='lessonaccesspermission',
            options={'ordering': ['-lesson_date', '-updated_at', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='lessonaccesspermission',
            name='unique_active_lesson_access_permission',
        ),
        migrations.AddField(
            model_name='lessonaccesspermission',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='lessonaccesspermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_lesson_access_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lessonaccesspermission',
            index=models.Index(fields=['student', 'lesson_date', 'subject'], name='academy_les_student_06c1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonaccesspermission',
            index=models.Index(fields=['access_type', 'is_active'], name='academy_les_access__97f12e_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonaccesspermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('teacher', 'student', 'lesson_date', 'subject', 'access_type'), name='unique_active_lesson_access_permission'),
        ),
        migrations.AddField(
            model_name='lessonaccessrequest',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='academy.lessonaccesspermission'),
        ),
        migrations.AddField(
            model_name='lessonaccessrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lesson_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonaccessrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_access_requests', to='academy.studentprofile'),
        ),
        migrations.AddField(
            model_name='lessonaccessrequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_access_requests', to='academy.teacherprofile'),
        ),
        migrations.DeleteModel(
            name='LessonWritePermission',
        ),
        migrations.AddIndex(
            model_name='lessonaccessrequest',
            index=models.Index(fields=['teacher', 'status'], name='academy_les_teacher_f7016f_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonaccessrequest',
            index=models.Index(fields=['student', 'lesson_date'], name='academy_les_student_b31283_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonaccessrequest',
            index=models.Index(fields=['request_type', 'status'], name='academy_les_request_0215ba_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonaccessrequest',
            index=models.Index(fields=['lesson_date', 'status'], name='academy_les_lesson__14943d_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonaccessrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('teacher', 'student', 'lesson_date', 'subject', 'request_type'), name='unique_pending_lesson_access_request'),
        ),
    ]
