# Generated by Django 5.2.14 on 2026-06-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_lessonaccessrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
