# Generated by Django 5.2.14 on 2026-06-04 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_add_duration_minutes_to_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_teacher_attendance_per_day',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='academy_att_teacher_29825f_idx',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=5),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['teacher', 'date', 'class_key'], name='academy_att_teacher_7c6779_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('entity_type', 'teacher', 'date', 'class_key'), name='unique_teacher_attendance_per_class'),
        ),
    ]
