# Generated by Django 5.2.14 on 2026-06-23 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_assign_existing_records_to_quran_department'),
        ('accounts', '0004_seed_tab_action_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlylessonsummary',
            name='unique_monthly_summary_per_student_subject',
        ),
        migrations.AddField(
            model_name='monthlylessonplan',
            name='plan_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlylessonsummary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlylessonsummary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='monthlylessonsummary',
            index=models.Index(fields=['student', 'start_date', 'end_date'], name='academy_mon_student_51675f_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlylessonsummary',
            index=models.Index(fields=['created_by', 'start_date', 'end_date'], name='academy_mon_created_951570_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlylessonsummary',
            constraint=models.UniqueConstraint(fields=('student', 'teacher', 'start_date', 'end_date', 'subject', 'created_by'), name='unique_summary_per_creator_student_range'),
        ),
    ]
