# Generated by Django 5.2.14 on 2026-07-16 14:37

import academy.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_student_history(apps, schema_editor):
    StudentProfile = apps.get_model("academy", "StudentProfile")
    StudentClassHistory = apps.get_model("academy", "StudentClassHistory")
    # Existing production students predate the Trial/Old field. Treat them as
    # established paid students so the migration does not turn the whole
    # academy into trial classes. Admins can adjust exceptions afterward.
    StudentProfile.objects.update(student_type="old_student", first_fee_paid=True)

    rows = []
    for student in StudentProfile.objects.select_related("user", "teacher").all().iterator():
        joined = getattr(student.user, "date_joined", None)
        effective_date = joined.date() if joined else django.utils.timezone.localdate()
        rows.append(StudentClassHistory(
            institution_id=student.institution_id or getattr(student.user, "institution_id", None),
            department_id=student.department_id or getattr(student.user, "department_id", None),
            student_id=student.id,
            event_type="enrolled",
            effective_date=effective_date,
            new_teacher_id=student.teacher_id,
            new_student_type=student.student_type,
            new_class_status=student.class_status,
            notes="Initial history created during Quran salary upgrade.",
        ))
    if rows:
        StudentClassHistory.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_remove_monthlylessonsummary_unique_monthly_summary_per_student_subject_and_more'),
        ('accounts', '0008_quran_management_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_status',
            field=models.CharField(choices=[('running', 'Running'), ('on_leave', 'On Leave'), ('old_dropped', 'Old Class Dropped'), ('trial_dropped', 'Trial Dropped'), ('old_dropped_other', 'Old Dropped (Other)'), ('not_counted', 'Not Counted Class')], db_index=True, default='running', max_length=40),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='half_month_salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='referral_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_students', to='academy.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='salary_class_mode',
            field=models.CharField(choices=[('standard', 'Standard class'), ('half_month', 'Half-month class')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='speaking_language',
            field=models.CharField(choices=[('english', 'English'), ('urdu', 'Urdu'), ('arabic', 'Arabic'), ('other', 'Other')], db_index=True, default='urdu', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status_effective_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('old_student', 'Old Student'), ('trial_student', 'Trial Student'), ('transferred_from_teacher', 'Transferred from another teacher'), ('returned_from_leave', 'Student return from leave'), ('transferred_to_teacher', 'Class transferred to another teacher')], db_index=True, default='trial_student', max_length=40),
        ),
        migrations.CreateModel(
            name='SalaryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_tiers', models.JSONField(default=academy.models.default_standard_salary_tiers)),
                ('three_day_tiers', models.JSONField(default=academy.models.default_three_day_salary_tiers)),
                ('bonus_rates', models.JSONField(default=academy.models.default_salary_bonus_rates)),
                ('achievement_payouts', models.JSONField(default=academy.models.default_achievement_payouts)),
                ('night_start', models.TimeField(default=datetime.time(22, 0))),
                ('night_end', models.TimeField(default=datetime.time(8, 30))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quran_salary_configuration', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quran_salary_configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enrolled', 'Enrolled'), ('profile_updated', 'Profile updated'), ('status_changed', 'Class status changed'), ('student_type_changed', 'Student type changed'), ('teacher_transfer', 'Teacher transfer'), ('returned_from_leave', 'Returned from leave'), ('first_fee_received', 'First fee received')], max_length=40)),
                ('effective_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('previous_student_type', models.CharField(blank=True, max_length=40)),
                ('new_student_type', models.CharField(blank=True, max_length=40)),
                ('previous_class_status', models.CharField(blank=True, max_length=40)),
                ('new_class_status', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_class_history', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.institution')),
                ('new_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history_new_teacher', to='academy.teacherprofile')),
                ('previous_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history_previous_teacher', to='academy.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='academy.studentprofile')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'effective_date'], name='academy_stu_student_34c365_idx'), models.Index(fields=['previous_teacher', 'effective_date'], name='academy_stu_previou_0caf68_idx'), models.Index(fields=['new_teacher', 'effective_date'], name='academy_stu_new_tea_d4e2a6_idx'), models.Index(fields=['event_type', 'effective_date'], name='academy_stu_event_t_52b04f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('behavior_good', models.BooleanField(default=False)),
                ('half_class_overrides', models.JSONField(blank=True, default=list)),
                ('other_bonuses', models.JSONField(blank=True, default=list)),
                ('override_values', models.JSONField(blank=True, default=dict)),
                ('calculated_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculated_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed')], default='draft', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salary_slips', to='accounts.department')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.institution')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_teacher_salary_slips', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='academy.teacherprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teacher_salary_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'teacher__user__first_name', 'teacher__user__username'],
                'indexes': [models.Index(fields=['department', 'year', 'month'], name='academy_tea_departm_6cd118_idx'), models.Index(fields=['teacher', 'year', 'month'], name='academy_tea_teacher_e557de_idx'), models.Index(fields=['status', 'year', 'month'], name='academy_tea_status_80274c_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'teacher', 'year', 'month'), name='unique_teacher_salary_slip_month')],
            },
        ),
        migrations.RunPython(seed_student_history, migrations.RunPython.noop),
    ]
