# Generated by Django 5.2.14 on 2026-10-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_quranteachermonthlypayroll_quransalaryledgerentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quransalaryadjustment',
            name='effect',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, default='credit', max_length=10),
        ),
    ]
