# Generated by Django 5.2.14 on 2026-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_quransalaryadjustment_effect'),
        ('accounts', '0010_repair_department_feature_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='effective_from',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='effective_to',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['student', 'effective_from', 'effective_to'], name='qsched_student_range'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['teacher', 'effective_from', 'effective_to'], name='qsched_teacher_range'),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='qsched_valid_date_range'),
        ),
    ]
