# Generated by Django 5.2.14 on 2026-10-04 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_class_schedule_history'),
        ('accounts', '0010_repair_department_feature_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quranclasscoverage',
            name='class_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Teacher session key in HH:MM format.', max_length=5),
        ),
        migrations.AddField(
            model_name='quranclasscoverage',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_coverages_v2', to='academy.classschedule'),
        ),
        migrations.AddField(
            model_name='quranclasscoverage',
            name='teacher_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_coverages_v2', to='academy.attendance'),
        ),
        migrations.AddIndex(
            model_name='quranclasscoverage',
            index=models.Index(fields=['department', 'date', 'class_key'], name='qcov_dept_session_v2'),
        ),
    ]
