# IVS attendance conditional uniqueness fix
# Generated by the IVS attendance import repair installer.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0022_coverage_session_audit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_teacher_attendance_per_class",
        ),
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_student_attendance_per_day",
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("teacher", "date", "class_key"),
                condition=models.Q(entity_type="teacher"),
                name="unique_teacher_attendance_per_class",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "date"),
                condition=models.Q(entity_type="student"),
                name="unique_student_attendance_per_day",
            ),
        ),
    ]
