# Generated by Django 5.2.14 on 2026-06-24 09:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0014_remove_monthlylessonsummary_unique_monthly_summary_per_student_subject_and_more'),
        ('accounts', '0004_seed_tab_action_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('board', models.CharField(choices=[('general', 'General'), ('federal', 'Federal Board'), ('igcse', 'IGCSE'), ('cambridge', 'Cambridge')], default='general', max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TuitionDepartmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_timezone', models.CharField(default='Asia/Karachi', max_length=80)),
                ('operating_start', models.TimeField(default=datetime.time(10, 0))),
                ('operating_end', models.TimeField(default=datetime.time(22, 0))),
                ('class_duration_minutes', models.PositiveSmallIntegerField(choices=[(40, '40 minutes')], default=40)),
                ('operating_weekdays', models.JSONField(blank=True, default=list)),
                ('allow_custom_start_times', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_config', to='accounts.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_configs', to='accounts.institution')),
            ],
        ),
        migrations.CreateModel(
            name='TuitionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_type', models.CharField(choices=[('regular', 'Regular Class'), ('crash', 'Crash Program')], default='regular', max_length=20)),
                ('custom_class_name', models.CharField(blank=True, max_length=150)),
                ('custom_subject_name', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='tuition.tuitionclasslevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tuition_enrollments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_enrollments', to='academy.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_enrollments', to='academy.teacherprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tuition_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__user__first_name', 'subject__sort_order', 'custom_subject_name'],
            },
        ),
        migrations.CreateModel(
            name='TuitionStandardSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('PK', 'Pakistan'), ('KSA', 'Saudi Arabia'), ('UAE', 'United Arab Emirates')], max_length=10)),
                ('timezone_name', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
            ],
            options={
                'ordering': ['region', 'sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TuitionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(editable=False)),
                ('timezone_name', models.CharField(default='Asia/Karachi', max_length=80)),
                ('meeting_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tuition_schedules', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.department')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tuition.tuitionenrollment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_schedules', to='academy.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_schedules', to='academy.teacherprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tuition_schedules', to=settings.AUTH_USER_MODEL)),
                ('standard_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='tuition.tuitionstandardslot')),
            ],
            options={
                'ordering': ['weekday', 'start_time', 'teacher__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TuitionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('is_standard', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tuitionenrollment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='tuition.tuitionsubject'),
        ),
        migrations.CreateModel(
            name='TuitionTeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone_name', models.CharField(default='Asia/Karachi', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tuition_availability', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_availability_periods', to='academy.teacherprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tuition_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher__user__first_name', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TuitionTeacherCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_capabilities', to='tuition.tuitionsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_subject_capabilities', to='academy.teacherprofile')),
            ],
            options={
                'ordering': ['teacher__user__first_name', 'subject__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TuitionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('target_model', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_audit_logs', to='accounts.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['department', 'created_at'], name='tuition_tui_departm_073d20_idx'), models.Index(fields=['actor', 'created_at'], name='tuition_tui_actor_i_5c4e53_idx'), models.Index(fields=['action', 'created_at'], name='tuition_tui_action_6088fd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tuitionclasslevel',
            index=models.Index(fields=['department', 'is_active'], name='tuition_tui_departm_060f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionclasslevel',
            index=models.Index(fields=['board', 'is_active'], name='tuition_tui_board_d41e9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='tuitionclasslevel',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_tuition_class_code_per_department'),
        ),
        migrations.AddConstraint(
            model_name='tuitionstandardslot',
            constraint=models.UniqueConstraint(fields=('department', 'region', 'label'), name='unique_tuition_standard_slot_label'),
        ),
        migrations.AddConstraint(
            model_name='tuitionstandardslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='tuition_standard_slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='tuitionschedule',
            index=models.Index(fields=['department', 'weekday', 'start_time'], name='tuition_tui_departm_4a6156_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionschedule',
            index=models.Index(fields=['teacher', 'weekday', 'is_active'], name='tuition_tui_teacher_cccdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionschedule',
            index=models.Index(fields=['student', 'weekday', 'is_active'], name='tuition_tui_student_85d8c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='tuitionschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('teacher', 'weekday', 'start_time'), name='unique_active_tuition_teacher_slot'),
        ),
        migrations.AddConstraint(
            model_name='tuitionschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'weekday', 'start_time'), name='unique_active_tuition_student_slot'),
        ),
        migrations.AddConstraint(
            model_name='tuitionschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='tuition_schedule_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='tuitionsubject',
            index=models.Index(fields=['department', 'is_active'], name='tuition_tui_departm_cefbd1_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionsubject',
            index=models.Index(fields=['is_standard', 'is_active'], name='tuition_tui_is_stan_0dd2ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='tuitionsubject',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_tuition_subject_code_per_department'),
        ),
        migrations.AddIndex(
            model_name='tuitionenrollment',
            index=models.Index(fields=['student', 'is_active'], name='tuition_tui_student_c4ca4a_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionenrollment',
            index=models.Index(fields=['teacher', 'is_active'], name='tuition_tui_teacher_27a1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionenrollment',
            index=models.Index(fields=['department', 'is_active'], name='tuition_tui_departm_20b1da_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionenrollment',
            index=models.Index(fields=['program_type', 'is_active'], name='tuition_tui_program_72a6a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='tuitionenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('subject__isnull', False)), fields=('student', 'subject'), name='unique_active_tuition_student_subject'),
        ),
        migrations.AddConstraint(
            model_name='tuitionenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('subject__isnull', True)), fields=('student', 'custom_subject_name'), name='unique_active_tuition_student_custom_subject'),
        ),
        migrations.AddConstraint(
            model_name='tuitionenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='tuition_enrollment_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='tuitionteacheravailability',
            index=models.Index(fields=['teacher', 'weekday', 'is_active'], name='tuition_tui_teacher_eaaf88_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionteacheravailability',
            index=models.Index(fields=['department', 'weekday', 'is_active'], name='tuition_tui_departm_f69f48_idx'),
        ),
        migrations.AddConstraint(
            model_name='tuitionteacheravailability',
            constraint=models.UniqueConstraint(fields=('teacher', 'weekday', 'start_time', 'end_time'), name='unique_tuition_teacher_availability_period'),
        ),
        migrations.AddConstraint(
            model_name='tuitionteacheravailability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='tuition_availability_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='tuitionteachercapability',
            index=models.Index(fields=['teacher', 'is_active'], name='tuition_tui_teacher_c80a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitionteachercapability',
            index=models.Index(fields=['subject', 'is_active'], name='tuition_tui_subject_c4a6ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='tuitionteachercapability',
            constraint=models.UniqueConstraint(fields=('department', 'teacher', 'subject'), name='unique_tuition_teacher_subject_capability'),
        ),
    ]
