# Generated by Django 5.2.14 on 2026-06-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_consolidate_tuition_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionenrollment',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='tuitionenrollment',
            name='schedule_country',
            field=models.CharField(blank=True, default='PK', max_length=12),
        ),
        migrations.AddField(
            model_name='tuitionenrollment',
            name='schedule_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuitionenrollment',
            name='schedule_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tuitionenrollment',
            name='schedule_slot',
            field=models.CharField(blank=True, default='PK_L1', max_length=24),
        ),
        migrations.AddField(
            model_name='tuitionenrollment',
            name='schedule_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
