# Generated by Django 5.2.14 on 2026-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_tuitionenrollment_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionteachercapability',
            name='available_schedule_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
