# Generated by Django 5.2.14 on 2026-07-08 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_remove_monthlylessonsummary_unique_monthly_summary_per_student_subject_and_more'),
        ('accounts', '0004_seed_tab_action_permissions'),
        ('tuition', '0005_tuitionteachercapability_available_schedule_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=20)),
                ('class_key', models.CharField(blank=True, max_length=80)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.department')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tuition.tuitionenrollment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.institution')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_tuition_attendance', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tuition.tuitionschedule')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_attendance_records', to='academy.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_attendance_records', to='academy.teacherprofile')),
            ],
            options={
                'ordering': ['-date', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['department', 'date'], name='tuition_tui_departm_1af6df_idx'), models.Index(fields=['schedule', 'date'], name='tuition_tui_schedul_07f3ea_idx'), models.Index(fields=['teacher', 'date'], name='tuition_tui_teacher_2dc369_idx'), models.Index(fields=['student', 'date'], name='tuition_tui_student_f2b86c_idx'), models.Index(fields=['entity_type', 'status'], name='tuition_tui_entity__fe4a01_idx')],
            },
        ),
    ]
